spring:
  devtools:
    livereload:
      enabled: true # 是否支持livereload
      port: 19901
    restart:
      enabled: true # 是否支持热部署
  datasource:
    druid:
      name: default
      url: jdbc:mysql://220.182.56.214:3306/sales_dev?useSSL=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
      username: root
      password: Gzadmin001!
      driverClassName: com.mysql.cj.jdbc.Driver
      dbType: mysql
      filters: stat
      initialSize: 0
      minIdle: 2
      maxWait: 3000
      maxActive: 10
      timeBetweenEvictionRunsMillis: 20000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 100
      logAbandoned: false
system:
  default:
    file:
      upload-path:/var/www/html/icallvtsnew
